# Used to start the base image with `docker compose up -d`

services:
  app:
    # image: ${IMAGE:-pkiraly/metadata-qa-marc}
    # image: ghcr.io/pkiraly/qa-catalogue:main
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./${INPUT:-input}:/opt/qa-catalogue/input
      - ./${OUTPUT:-output}:/opt/qa-catalogue/output
      - ./logs:/opt/qa-catalogue/logs
      - ./solr:/opt/solr
      - ./catalogues:/opt/qa-catalogue/catalogues
      - ./web-classes/catalogue:/var/www/html/qa-catalogue/classes/catalogue
      - ./${WEBBCONFIG:-web-config}:/var/www/html/qa-catalogue/config
      - /etc/timezone:/etc/timezone:ro    # Sync timezone
      - /etc/localtime:/etc/localtime:ro  # Sync localtime
      - ./apache2/sites-available:/etc/apache2/sites-available
    ports:
      - "${WEBPORT:-8000}:80"       # qa-catalogue-web
      - "${SOLRPORT:-8983}:8983"  # Solr
    container_name: ${CONTAINER:-metadata-qa-marc}
