# Used to start the base image with `docker compose up -d`

version: '2'

services:
  app:
    container_name: metadata-qa-marc
    # image: ${IMAGE:-pkiraly/metadata-qa-marc:0.7.0}
    # image: ghcr.io/pkiraly/qa-catalogue:main
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./${INPUT:-input}:/opt/qa-catalogue/input
      - ./${OUTPUT:-output}:/opt/qa-catalogue/output
      - ./catalogues:/opt/qa-catalogue/catalogues
    ports:
      - "${WEBPORT:-8000}:80"       # qa-catalogue-web
      - "${SOLRPORT:-8983}:8983"  # Solr
