# Used to start the base image with `docker compose up -d`

version: '2'

services:
  app:
    image: ${IMAGE:-pkiraly/metadata-qa-marc:0.7.0}
    volumes:
      - ./${INPUT:-input}:/opt/qa-catalogue/marc
      - ./${WEBBCONFIG:-web-config}:/var/www/html/qa-catalogue/config
    ports:
      - "${WEBPORT:-80}:80"       # qa-catalogue-web
      - "${SOLRPORT:-8983}:8983"  # Solr
      - /etc/timezone:/etc/timezone:ro # Sync timezone
      - /etc/localtime:/etc/localtime:ro # Sync localtime
    container_name: ${CONTAINER:-metadata-qa-marc}
